-- ============================================
-- Sprint 2.2: Demo Events Seed Data
-- 20 realistic events around Kyiv
-- ============================================

-- First, ensure we have a demo organizer profile
-- This assumes there's already a profile with user_id = auth.uid()
-- In production, this would be created during onboarding

-- Helper function to get or create a demo organizer
DO $$
DECLARE
    demo_user_id UUID;
    demo_profile_id UUID;
BEGIN
    -- Get any existing profile to use as organizer
    SELECT id INTO demo_profile_id
    FROM public.profiles
    LIMIT 1;
    
    -- If no profile exists, we'll use NULL and let the events be created without organizers
END $$;

-- ============================================
-- DEMO EVENTS: 20 events around Kyiv
-- Different categories, locations, organizers, and dates
-- ============================================

INSERT INTO public.events (
    title,
    description,
    category,
    event_type,
    latitude,
    longitude,
    location_name,
    location_address,
    event_date,
    event_end_date,
    max_participants,
    current_participants,
    price,
    currency,
    photo_url,
    status,
    requires_approval,
    is_premium_only,
    organizer_id
) VALUES
-- SOCIALIZATION (5 events)
(
    'Ранкова кава на Подолі',
    'Зустріч для нетворкінгу та нових знайомств. Приєднуйся до нас на ранню каву з краєвидом на Дніпро!',
    'party',
    'in_person',
    50.4645,
    30.5234,
    'Кофейня "Живой Кофе"',
    'вул. Сагайдачного 25, Київ',
    NOW() + INTERVAL '2 days 9:00',
    NOW() + INTERVAL '2 days 11:00',
    12,
    3,
    0,
    'UAH',
    'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=400',
    'active',
    false,
    false,
    NULL
),
(
    'Вечір настільних ігор',
    'Класичні та нові настільні ігри. Всі рівні вітаються! Bring your own or play ours.',
    'party',
    'in_person',
    50.4501,
    30.5100,
    'Graff Bar',
    'вул. Хрещатик 15, Київ',
    NOW() + INTERVAL '3 days 18:00',
    NOW() + INTERVAL '3 days 22:00',
    20,
    7,
    100,
    'UAH',
    'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=400',
    'active',
    false,
    false,
    NULL
),
(
    'Пікнік у парку',
    'Спонтанний пікнік на траві. Приносимо свою їжу та напої. Ідеально для розслабленого спілкування.',
    'party',
    'in_person',
    50.4415,
    30.4567,
    'Парк ім. Шевченка',
    'Парк Шевченка, центральна галявина, Київ',
    NOW() + INTERVAL '5 days 14:00',
    NOW() + INTERVAL '5 days 18:00',
    25,
    12,
    0,
    'UAH',
    'https://images.unsplash.com/photo-1528164344705-47542687000d?w=400',
    'active',
    false,
    false,
    NULL
),
(
    'Open Mic Night',
    'Запрошуємо музикантів, коміків, поетів показати свої таланти. Аудиторія вітається!',
    'party',
    'in_person',
    50.4855,
    30.4867,
    ' Closer Cafe',
    'вул. Нижній Вал 19, Київ',
    NOW() + INTERVAL '7 days 19:00',
    NOW() + INTERVAL '7 days 23:00',
    50,
    23,
    150,
    'UAH',
    'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=400',
    'active',
    false,
    false,
    NULL
),
(
    'Sunday Brunch Meetup',
    'Невимушений сімейний сніданок. Знайомства без тиску та очікувань.',
    'party',
    'in_person',
    50.4589,
    30.5123,
    'Citronium Mandarin',
    'вул. Велика Васильківська 57, Київ',
    NOW() + INTERVAL '10 days 11:00',
    NOW() + INTERVAL '10 days 14:00',
    15,
    5,
    350,
    'UAH',
    'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400',
    'active',
    false,
    false,
    NULL
),

-- SPORTS (4 events)
(
    'Ранкова пробіжка в парку',
    'Безкоштовна групова пробіжка 5-7 км. Всі рівні підготовки. Старт від головного входу.',
    'sport',
    'in_person',
    50.4474,
    30.4534,
    'Парк Шевченка',
    'Головний вхід парку, Київ',
    NOW() + INTERVAL '1 day 7:00',
    NOW() + INTERVAL '1 day 8:30',
    30,
    14,
    0,
    'UAH',
    'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=400',
    'active',
    false,
    false,
    NULL
),
(
    'Йога на даху',
    'Сесія його-терапії на даху з видом на Київ. Килимки надані.',
    'sport',
    'in_person',
    50.4501,
    30.5225,
    'Hotel Ukr',
    'вул. Хрещатик 54, дах, Київ',
    NOW() + INTERVAL '4 days 8:00',
    NOW() + INTERVAL '4 days 9:30',
    20,
    8,
    200,
    'UAH',
    'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    'active',
    false,
    false,
    NULL
),
(
    'Велопрогулянка Подолом',
    'Легка велопрогулянка історичним Подолом. Маршрут ~15 км.',
    'sport',
    'in_person',
    50.4691,
    30.5261,
    'Андріївський узвіз',
    'Андріївський узвіз, Київ',
    NOW() + INTERVAL '6 days 10:00',
    NOW() + INTERVAL '6 days 13:00',
    15,
    6,
    0,
    'UAH',
    'https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=400',
    'active',
    false,
    false,
    NULL
),
(
    'Football на Оболоні',
    'Аматорський футбол 5x5. Шукаємо 2 гравці до команді!',
    'sport',
    'in_person',
    50.5267,
    30.4989,
    'Спортивний майданчик Оболонь',
    'Набережна Оболонська 14, Київ',
    NOW() + INTERVAL '8 days 17:00',
    NOW() + INTERVAL '8 days 19:00',
    10,
    9,
    0,
    'UAH',
    'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400',
    'active',
    false,
    false,
    NULL
),

-- FOOD (3 events)
(
    'Кулінарний мастер-клас',
    'Навчимося готувати пасту та десерти від шеф-кухаря. Всі інгредієнти надані.',
    'food',
    'in_person',
    50.4501,
    30.5300,
    'Кухня Studio',
    'вул. Богдана Хмельницького 32, Київ',
    NOW() + INTERVAL '3 days 15:00',
    NOW() + INTERVAL '3 days 18:00',
    8,
    6,
    450,
    'UAH',
    'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=400',
    'active',
    false,
    false,
    NULL
),
(
    'Вулична їжа фестиваль',
    'Найкращі фудтраки Києва в одному місці. Дегустація стрітфуду.',
    'food',
    'in_person',
    50.4444,
    30.4523,
    'Пocaдка',
    'Пocaдка, Київ',
    NOW() + INTERVAL '9 days 12:00',
    NOW() + INTERVAL '9 days 20:00',
    100,
    45,
    0,
    'UAH',
    'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400',
    'active',
    false,
    false,
    NULL
),
(
    'Кавовий дегустацій',
    'Подорож у світ кави: від зерна до чашки. 5 різних сортів.',
    'food',
    'in_person',
    50.4623,
    30.5145,
    'Svit Kavy',
    'вул. Пушкінська 5, Київ',
    NOW() + INTERVAL '12 days 11:00',
    NOW() + INTERVAL '12 days 13:00',
    12,
    4,
    300,
    'UAH',
    'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=400',
    'active',
    false,
    false,
    NULL
),

-- MUSIC (2 events)
(
    'Dj Workshop',
    'Навчіться мікшувати від професійного DJ. Устаткування надане.',
    'music',
    'in_person',
    50.4789,
    30.4956,
    'Beat Pitch',
    'вул. Межигірська 82, Київ',
    NOW() + INTERVAL '5 days 14:00',
    NOW() + INTERVAL '5 days 18:00',
    10,
    7,
    500,
    'UAH',
    'https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=400',
    'active',
    false,
    false,
    NULL
),
(
    'Акустичний концерт',
    'Живий акустичний виступ local musicians. Кава та атмосфера.',
    'music',
    'in_person',
    50.4523,
    30.5189,
    'Belief Coffee',
    'вул. Велика Житомирська 4, Київ',
    NOW() + INTERVAL '14 days 19:00',
    NOW() + INTERVAL '14 days 22:00',
    40,
    18,
    200,
    'UAH',
    'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400',
    'active',
    false,
    false,
    NULL
),

-- ART (2 events)
(
    'Street Art Tour',
    'Екскурсія кращими графіті та стріт-арт локаціями Києва з гідом.',
    'art',
    'in_person',
    50.4645,
    30.4989,
    'Точка збору: метро Лівобережна',
    'метро Лівобережна, Київ',
    NOW() + INTERVAL '4 days 15:00',
    NOW() + INTERVAL '4 days 18:00',
    15,
    9,
    250,
    'UAH',
    'https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=400',
    'active',
    false,
    false,
    NULL
),
(
    'Арт-терапія для початківців',
    'Розкрийте свій творчий потенціал через живопис. Всі матеріали включено.',
    'art',
    'in_person',
    50.4432,
    30.5234,
    'Kaleidoscop',
    'вул. Володимирська 16, Київ',
    NOW() + INTERVAL '11 days 16:00',
    NOW() + INTERVAL '11 days 19:00',
    12,
    3,
    400,
    'UAH',
    'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400',
    'active',
    false,
    false,
    NULL
),

-- TECHNOLOGY (1 event)
(
    'Tech Meetup: AI & Startups',
    'Обговорення трендів AI у стартапах. Пітчинги та нетворкінг.',
    'networking',
    'in_person',
    50.4501,
    30.5356,
    'Platforma',
    'вул. Хрещатик 14, Київ',
    NOW() + INTERVAL '6 days 18:00',
    NOW() + INTERVAL '6 days 21:00',
    80,
    34,
    0,
    'UAH',
    'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400',
    'active',
    false,
    false,
    NULL
),

-- EDUCATION (1 event)
(
    'Мова жестів: базовий курс',
    'Вивчіть основи української мови жестів. Корисно для всіх.',
    'education',
    'in_person',
    50.4678,
    30.5123,
    'Бібліотека ім. Вернадського',
    'просп. Голосіївський 87, Київ',
    NOW() + INTERVAL '8 days 14:00',
    NOW() + INTERVAL '8 days 16:00',
    20,
    7,
    0,
    'UAH',
    'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400',
    'active',
    false,
    false,
    NULL
),

-- GAMES (1 event)
(
    'Турнір з CS2',
    'Командний турнір з Counter-Strike 2. 5x5. Призи для переможців!',
    'games',
    'in_person',
    50.4756,
    30.4878,
    'Cyber Arena Kyiv',
    'вул. Січових Стрільців 52, Київ',
    NOW() + INTERVAL '10 days 12:00',
    NOW() + INTERVAL '10 days 20:00',
    20,
    15,
    150,
    'UAH',
    'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400',
    'active',
    false,
    false,
    NULL
),

-- NATURE (1 event)
(
    'Похід на Вишгород',
    'Піший похід до Вишгорода. Маршрут ~18 км. Природа та історія.',
    'nature',
    'in_person',
    50.5890,
    30.4890,
    'Точка збору: метро Героїв Дніпра',
    'метро Героїв Дніпра, Київ',
    NOW() + INTERVAL '13 days 9:00',
    NOW() + INTERVAL '13 days 16:00',
    25,
    11,
    0,
    'UAH',
    'https://images.unsplash.com/photo-1551632811-561732d1e306?w=400',
    'active',
    false,
    false,
    NULL
);

-- Verify count
SELECT 'Demo events created: ' || COUNT(*) || ' events' AS result
FROM public.events
WHERE status = 'active' 
AND deleted_at IS NULL
AND event_date > NOW();
